### ISSUE TITLE
Doc string

### ISSUE THREAD

**Issue by fatalayalbayrak** [idincer944/selenium_case#4]
her fonksiyon ne iş yaptığını açıklamalı buna göre doc string eklenmeli örneğin:
"""Gets comment text
param int index: comment index you want to act with
"""
parametre varsa fonksiyonda parametre de eklenmeli ve parametrenin hangi tipte veri aldığı belirtilmeli int, string vs.

https://github.com/idincer944/selenium_case/blob/9b8418a80070b8a0d428d445966eb752686bfb90/poms/admin_login_page_objects.py#L17

**Comment by idincer944** [comment]
I added these when I was closing issue #2
